---
- name: Install handy packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - htop
    - tree
    - curl
    - cowsay
    - fortune-mod

- name: Set locale to en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Sync node timezone
  file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/Asia/Shanghai
    state: link
    force: yes

- name: "`fortune | cowsay` on bash startup"
  lineinfile:
    dest: /etc/profile.d/zzz-cowsay.sh
    line: "/usr/games/fortune | /usr/games/cowsay 2> /dev/null"
    create: yes

- name: Refine bash history
  lineinfile:
    dest: /etc/profile.d/history-with-timestamp.sh
    line: "{{ item }}"
    create: yes
  with_items:
    - 'export HISTTIMEFORMAT="%F %T "'
    - "export HISTSIZE={{ history_size // 2}}"
    - "export HISTFILESIZE={{ history_size }}"

- name: Manage behaviour of line input editing
  template:
    dest: /etc/inputrc
    src: inputrc.j2
...
